### ISSUE TITLE
Fall back to common dataset if seed file is missing in specified dataset

### ISSUE THREAD

**Issue by ronwsmith** [centro/application_seeds#5]
With a common fallback dataset, you could avoid copying and pasting the same data between datasets.  Easier maintenance and less overhead when implementing new datasets.

I'm picturing this as a file-level fallback (if specified file is missing, use the common one), not merging the data with the common one.

**Comment by jwood** [comment]
This has been fixed in version 0.4.0 of the library (https://github.com/centro/application_seeds/pull/6).
